apiVersion: v1
kind: Service
metadata:
  name: drovery-api
  labels: { app: drovery, role: api }
spec:
  type: ClusterIP
  selector: { app: drovery, role: api }
  ports:
    - { name: http, port: 80, targetPort: http, protocol: TCP }
